/*
 * ITU API
 *
 * Nice api yep
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Student struct {

	Name string `json:"name,omitempty"`

	Id int32 `json:"id,omitempty"`
}
