/*
 * ITU API
 *
 * Nice api yep
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Course struct {

	Name string `json:"name,omitempty"`

	CourseID int32 `json:"courseID,omitempty"`
}
