---
swagger: "2.0"
info:
  description: "Nice api yep"
  version: "1.0.0"
  title: "ITU API"
paths:
  /student:
    post:
      summary: "Add a new Student"
      parameters:
      - in: "body"
        name: "body"
        description: "Student object to be added"
        required: true
        schema:
          $ref: "#/definitions/Student"
        x-exportParamName: "Body"
      responses:
        "200":
          description: "Ok boss"
        "405":
          description: "Invalid input"
  /Student/{id}:
    get:
      summary: "Get a by student ID"
      parameters:
      - name: "id"
        in: "path"
        description: "Student object to be retrieved"
        required: true
        type: "integer"
        format: "int32"
        x-exportParamName: "Id"
      responses:
        "200":
          description: "Ok boss"
          schema:
            $ref: "#/definitions/Student"
        "405":
          description: "Invalid input"
  /course:
    post:
      summary: "Add a new course"
      parameters:
      - in: "body"
        name: "body"
        description: "Course object to be added"
        required: true
        schema:
          $ref: "#/definitions/Course"
        x-exportParamName: "Body"
      responses:
        "200":
          description: "Ok boss"
        "405":
          description: "Invalid input"
  /Course/{id}:
    get:
      summary: "Get a by Course ID"
      parameters:
      - name: "id"
        in: "path"
        description: "Course object to be retrieved"
        required: true
        type: "integer"
        format: "int32"
        x-exportParamName: "Id"
      responses:
        "200":
          description: "Ok boss"
          schema:
            $ref: "#/definitions/Course"
        "405":
          description: "Invalid input"
    put:
      summary: "Update an existing Course"
      parameters:
      - name: "id"
        in: "path"
        description: "Course object to update"
        required: true
        x-exportParamName: "Id"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Course not found"
        "405":
          description: "Validation exception"
    delete:
      summary: "Deletes a Course"
      parameters:
      - name: "id"
        in: "path"
        description: "Pet id to delete"
        required: true
        type: "integer"
        format: "int64"
        x-exportParamName: "Id"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Course not found"
definitions:
  Student:
    type: "object"
    properties:
      name:
        type: "string"
      id:
        type: "integer"
        format: "int32"
    example:
      name: "name"
      id: 0
  Course:
    type: "object"
    properties:
      name:
        type: "string"
      courseID:
        type: "integer"
        format: "int32"
    example:
      name: "name"
      courseID: 0
  Teacher:
    type: "object"
    properties:
      name:
        type: "string"
      id:
        type: "integer"
        format: "int32"
      course:
        type: "object"
        properties:
          teachingCourse:
            $ref: "#/definitions/Course"
